# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.internal.http.connectionTimeout=120000
org.gradle.internal.http.socketTimeout=120000
org.gradle.workers.max=2

# Mod Properties
mod_id=tablist
mod_name=Tab List
mod_license=All Rights Reserved
mod_version=1.5
mod_group_id=com.sennecools.tablist
mod_authors=sennecools, NeofastFTL
mod_description=A customizable tab list and chat formatter with animated headers/footers, AFK detection, player sorting, and optional FTB Ranks, LuckPerms, and spark integrations.

# Publishing
group=com.sennecools.tablist
version=1.5
